#!/usr/bin/env python3
"""Activity-aware drift signal for lessons / practices.

For each lesson / practice that declares ``applies_to`` paths in its YAML
frontmatter, check whether any of those paths have been modified in git
history since the doc's ``last_validated_at`` date. Output a summary
to ``docs/lessons/_drift_report.md`` so the next AI session that touches
related code knows which docs are candidates for re-validation.

The report is **non-blocking**: drift is signal, not error. The actual
re-validation happens via the use-driven mechanism documented in the
project's CLAUDE.md / AGENTS.md (and in this skill's
``references/lifecycle-protocols.md``).

Modes
-----
- ``--write``  : (default) regenerate ``docs/lessons/_drift_report.md``.
- ``--check``  : compare regenerated content against on-disk; exit 1 on diff.

Skips docs that lack ``applies_to`` (cannot be drift-checked) or
``last_validated_at`` (no since-when reference point).

Installation
------------
This script is shipped by the Claude Code skill ``knowledge-discipline``.
Copy it into your project's ``tools/`` directory and run from the project
root. Requires the project to be a git working tree.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DOCS_ROOT = PROJECT_ROOT / "docs"
REPORT_PATH = DOCS_ROOT / "lessons" / "_drift_report.md"


def _parse_frontmatter(text: str) -> dict | None:
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end < 0:
        return None
    block = text[4:end].splitlines()
    data: dict = {}
    current_list_key: str | None = None
    for line in block:
        if not line.strip():
            current_list_key = None
            continue
        if line.startswith("  - ") and current_list_key is not None:
            value = line[4:].strip().strip('"').strip("'")
            data[current_list_key].append(value)
            continue
        m = re.match(r"^([\w_]+):\s*(.*)$", line)
        if not m:
            current_list_key = None
            continue
        key, value = m.group(1), m.group(2).strip()
        if not value:
            data[key] = []
            current_list_key = key
            continue
        data[key] = value.strip('"').strip("'")
        current_list_key = None
    return data


def _git_log_changes(path: str, since: str) -> list[str]:
    """Return commit subjects (oneline) that touched ``path`` since ``since``."""
    try:
        result = subprocess.run(
            ["git", "log", f"--since={since}", "--oneline", "--no-merges", "--", path],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
    except subprocess.CalledProcessError:
        return []
    except FileNotFoundError:
        # `git` not installed
        return []
    return [line for line in result.stdout.splitlines() if line.strip()]


def _scan_knowledge_docs() -> list[tuple[str, dict]]:
    found: list[tuple[str, dict]] = []
    for sub in ("lessons", "practices"):
        sub_root = DOCS_ROOT / sub
        if not sub_root.is_dir():
            continue
        for path in sorted(sub_root.rglob("*.md")):
            if path.name.startswith("_") or path.name == "README.md":
                continue
            text = path.read_text(encoding="utf-8")
            fm = _parse_frontmatter(text)
            if fm is None:
                continue
            rel = path.relative_to(DOCS_ROOT).as_posix()
            found.append((rel, fm))
    return found


def _build_report() -> str:
    docs = _scan_knowledge_docs()
    drifts: list[dict] = []
    skipped_no_applies = 0
    skipped_no_validation_date = 0

    for rel, fm in docs:
        applies_to = fm.get("applies_to") or []
        if not applies_to:
            skipped_no_applies += 1
            continue
        last_validated = str(fm.get("last_validated_at") or "").strip()
        if not last_validated:
            skipped_no_validation_date += 1
            continue
        per_path: dict[str, list[str]] = {}
        for code_path in applies_to:
            commits = _git_log_changes(code_path, last_validated)
            if commits:
                per_path[code_path] = commits[:5]
        if per_path:
            drifts.append({
                "doc": rel,
                "title": str(fm.get("title", rel)).strip(),
                "last_validated_at": last_validated,
                "drifts": per_path,
            })

    out: list[str] = [
        "<!-- AUTO-GENERATED by tools/docs_drift_signal.py — do not hand-edit -->",
        "",
        "# Lesson / practice drift report",
        "",
        f"Knowledge docs scanned: {len(docs)}",
        f"With drift candidates: **{len(drifts)}**",
        f"Skipped (no `applies_to`): {skipped_no_applies}",
        f"Skipped (no `last_validated_at`): {skipped_no_validation_date}",
        "",
    ]

    if not drifts:
        out.append("No drift candidates. All knowledge docs are in sync with their `applies_to` paths since their `last_validated_at`.")
        out.append("")
    else:
        out.append("## Candidates")
        out.append("")
        out.append("Each entry below: a knowledge doc whose declared `applies_to` paths have")
        out.append("changed since `last_validated_at`. Per the project's use-driven validation")
        out.append("rule, the next dev_log / commit / PR that cites one of these docs should")
        out.append("also process its frontmatter (bump / refine / deprecate).")
        out.append("")
        for d in drifts:
            doc_rel = d["doc"]
            if doc_rel.startswith("lessons/"):
                href = doc_rel[len("lessons/"):]
            else:
                href = "../" + doc_rel
            out.append(f"### [{d['title']}]({href})")
            out.append("")
            out.append(f"- Doc: `{d['doc']}`")
            out.append(f"- Last validated: {d['last_validated_at']}")
            out.append("- Recent commits touching `applies_to` paths:")
            for code_path, commits in d["drifts"].items():
                out.append(f"  - `{code_path}`:")
                for commit in commits:
                    out.append(f"    - {commit}")
            out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if not args.write and not args.check:
        args.write = True

    if not (PROJECT_ROOT / ".git").exists():
        print(
            f"ERROR: not a git working tree at {PROJECT_ROOT}. "
            "docs_drift_signal needs git history to detect drift; "
            "initialize the repo first (`git init`) or move the script into a git project.",
            file=sys.stderr,
        )
        return 2

    rendered = _build_report()

    if args.check:
        existing = REPORT_PATH.read_text(encoding="utf-8") if REPORT_PATH.exists() else ""
        if existing != rendered:
            print(
                "ERROR: docs/lessons/_drift_report.md is stale. "
                "Run `python tools/docs_drift_signal.py --write` and commit.",
                file=sys.stderr,
            )
            return 1
        print("OK: drift report up to date")
        return 0

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {REPORT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
